TeamCity-Kobiton
kobiton/TeamCity-Appium-ReactNative pull request #3
Opened 2018-08-08 01:52 UTC by phanthaoIT

2018-08-14 03:36 UTC, blackheat commented on 1-run-automation-test.md
> +  + Oracle java 8 and updates
I think that the word "higher" should be used instead of "updates" :D

2018-08-14 03:38 UTC, blackheat commented on 1-run-automation-test.md
> +This part will guide you setup TeamCity and configure TeamCity with GitHub. Skip step if you already have TeamCity setup.
*guide you how to setup

2018-08-14 03:39 UTC, blackheat commented on 1-run-automation-test.md
> + + For introduce on how to install and configure the TeamCity server, follow [this guide](https://confluence.jetbrains.com/display/TCD18/Installing+and+Configuring+the+TeamCity+Server).
"introduction" should be used instead of "introduce"

2018-08-14 03:42 UTC, blackheat commented on 1-run-automation-test.md
> +**a. Get Desired cap**
I think that "desiredCaps" should be used instead of "desired cap", so as to match the variable in the provided js example.

2018-08-14 03:45 UTC, blackheat commented on 1-run-automation-test.md
> ++ In your project in TeamCity, on the left side on the page, click on 'Parameters'. Then click buton `Add new parameter`.
I think that "then click the "Add new parameter" button" should be used.

2018-08-14 03:46 UTC, blackheat commented on 1-run-automation-test.md
> ++ Now, try a build on Teamity and check Kobiton cloud devices to see if a test session was created.
*try to build on TeamCity

2018-08-14 03:57 UTC, blackheat commented on 1-run-automation-test.md
> ++ Make sure in the code you specify your Kobiton username, API key and replace the `desiredCaps`.
*desiredCaps with the one from Kobiton automation settings

2018-08-14 04:00 UTC, blackheat commented on 1-run-automation-test.md
> +Kobiton already provide an script using NodeJS to get session information. For samples of get session, go to https://github.com/kobiton/samples and select the folder named 'REST API'. You can downloa
*provided a script.
*examples of how to get session(s) information, get session commands (list all of the functions that the REST API folder provides, or instead just say that "examples of how to interact with session(s)").
*can download, not "downloads"
*repository, not "reposity".

2018-08-14 04:04 UTC, blackheat commented on 1-run-automation-test.md
> ++ In your project in TeamCity, on the left side on the page, click on 'Parameters'. Then click buton `Add new parameter`.
I think that "click 'Parameters'" should be used (omitting "on").

2018-08-14 04:18 UTC, blackheat commented on 1-run-automation-test.md
> ++ In your project in TeamCity, on the left side on the page, click on 'Parameters'. Then click buton `Add new parameter`.
"left side on the page" > "left side of the page".

2018-08-14 04:28 UTC, blackheat commented on 1-run-automation-test.md
> + Kobiton provides the so-called Automation Settings for each device on which you want to run tests. Actually Automation Settings are the desired capabilities that need to be added to the Appium test
"in order tests" > "in order for tests"

2018-08-15 07:20 UTC, tiennguyenhoan requested changes
Please take a look !

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> + + You can download TeamCity from [here](https://www.jetbrains.com/teamcity/download/).
I saw the link below already have content of guiding to install teamCity. Is it necessary to have this sentence here?

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> ++ More information about TeamCity can be found in [this tutorial](https://confluence.jetbrains.com/display/TCD10/TeamCity+Documentation).
```
> For more information about
```
Purpose: Make it separate with the content because it is just an extra information.

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +## 2. Prepare Kobiton configuration for executing automation testing
I think this part doesn't need to be separate.

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> + ![alt text](./assets/automation.png )
please capture image of app type to `app`

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> + + Hover over any device and click on the Automation settings button. A dialog box will then appear on screen.
Hover over any device THAT YOU WANT TO TEST WITH  and click ...

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +## 3. Write the automation test script
Suggestion content:
```
## 3.Run automation test on Kobiton devices
### 3.1 Prepare automation test script
     If you do not have a Kobiton account yet, go ahead to [create a free trial account](https://kobiton.com/freetrial/) and sign in. It takes just a few moments.
    > You can visit [our blog](https://kobiton.com/blog/automation-web-appium-kobiton-nodejs/) for more detail in setting up an automation test script. 

- Username and API key
      Go to https://portal.kobiton.com to get your *Username* and *API key*.
            
- Desired capabilities
      Kobiton provides the so-called Automation Settings for each device on which you want to run tests. Actually Automation Settings are the desired capabilities that need to be added to the Appium test script in order for tests to be executed on the Kobiton devices.

....

+ On the left hand side, you can select your preferred language, App Type, etc.
> For this the sample, we use `NodeJS` as the language. 

- Write automation test script
Kobiton already provide some example for basic automation test.
    -    Go to https://github.com/kobiton/samples 
    -    Clone the repo to your local machine 
    -    Choose the testing language, with this sample we use `NodeJS` 
    -    Open testing file, you can choose wherever  testing on Android or Ios. Make sure open the `app` script, not the `web`

Replace the Kobiton `Username`, `API key` and `desiredCaps` that collected from above part to the script
~~~
const username = <YOUR KOBITON USERNAME>
const apiKey = <YOUR KOBITON API KEY>

const kobitonServerConfig = {
  protocol: 'https',
  host: 'api.kobiton.com',
  auth: `${username}:${apiKey}`
}

var desiredCaps = {
  sessionName:        'Automation test session',
  sessionDescription: '', 
  deviceOrientation:  'portrait',  
  captureScreenshots: true,  
  browserName:        'chrome', 
  deviceGroup:        'KOBITON', 
  deviceName:         'G Pad 8.0',
  platformVersion:    '5.0.2',
  platformName:       'Android' 
}
~~~
>Note: Please recheck the script desiredCaps before run it. 

```

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> + **b. Run automation test**
Follow the guide

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +You can attach an enviroment variable to TeamCity(Optional).
what do you mean by this ?

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> ++ In your project in TeamCity, on the left side on the page, click on 'Build Step' to set build steps.
``` In your teamCity project, ```

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> ++ Add command lines to your script content.
``` Add below commands to `Custom script` part ```

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +Example:
Remove this

2018-08-15 07:20 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> ++ Now, try to build on Teamity and check Kobiton cloud devices to see if a test session was created.
How can I build it? Where can I check the session Created ?

2018-08-16 08:10 UTC, tiennguyenhoan requested changes
@phanthaoIT Final !

2018-08-16 08:10 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +## 1. Setup TeamCity
``` 
## 1. Config TeamCity with github Repository
```

2018-08-16 08:10 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +This guide will demonstrate how to run an automation test with Kobiton on Teamcity.
This guide will demonstrate how to run automation test on Kobiton devices with TeamCity through git hub repository.

2018-08-16 08:10 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +## Table of contents
## Table of contents
- Prerequisites
- Config Travis CI and integrate with Github
- Config automation test script 
- Run automation test on Kobiton devices
     - Config teamcity
     - Execute test script
- Fetch test session data through Kobiton REST API

2018-08-16 08:10 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +## 2. Write the automation test script
```## 2.Config automation test script```

2018-08-16 08:10 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +> Kobiton already provide samples for automation test script on multiple languages. Visit [here](https://github.com/kobiton/samples) for references.
This documentation will use NodeJS as the default language to demonstrate the guide. Therefore, Integrate NodeJs plugin to Travis Ci is required.
> If you do not know how to integrate a Node JS app with Travis CI, follow {this tutorial]()

2018-08-16 08:10 UTC, tiennguyenhoan commented on 1-run-automation-test.md
> +**This guideline will use a Node JS script as an example.**
Remove this line

2018-08-16 08:10 UTC, NguyenHoanTien commented on 1-run-automation-test.md
> +### 2.1 Prepare automation tese script
Please follow this template 
```
## Config automation test script
### 1. Get Username and Api key
Go to https://portal.kobiton.com

    - Username 
       * Select *user Icon* -> 'Profile' (you might find it in the top right conner)
       <Image with border username part>

    - Api Key
       * Select *user Icon* -> 'Settings' (you might find it in the top right conner)
       <Image with border Api key part>

### 2. Get desired capabilities
The desired capabilities need to be added to the automation test script in order tests to be executed on the Kobiton device.
      * Click *Devices* in the top navigation bar
         <image>
      * Hover over any device you want to test with and click on the Automation settings button (the gear symbol)
         <Image, border>
      * On the left hand side, you can select your preferred language, App Type, etc.
        > For this the sample, we use `NodeJS` as the language to run automation test. 
         <Image, border>

### 3. Config TeamCity project
Follow step below to setup TeamCity for automation testing
        1. In your Teamcity project, click on 'Build Step' on the left side on the page, to open `Build Step` session.
        2. For the `'Runner type'` category, choose `'Command Line'`
        3. Set `Custom script` for `Run` field
        3. Add below command to `Custom script` part
            ~~~
                <Script>
            ~~~
*(Optional) Attaching environment variable to Teamcity
      - In your project....

### 4. Config automation test project
- Kobiton already provides sample for automation test, visit [here]() 
Replace the ....
~~~
<Desired Caps>
~~~
## Run automation test on Kobiton devices
Push code to github ....

- Result
     - Show TeamCity is running (capture screenshot )
     - Show Kobiton automation is running (Session -> capture screenshot)
     
## Fetch session data with Kobiton REST API
`REST API` -> `rest-api` folder 
https://github.com/kobiton/samples/rest-api
```

2018-08-16 11:02 UTC, thangvo38 requested changes
Reviewed

2018-08-16 11:02 UTC, thangvo38 commented on 1-run-automation-test.md
> +  + Select *user Icon* -> 'Profile' (you might find it in the top right conner)
```
*Profile*
```
```
*Settings*
```

2018-08-16 11:02 UTC, thangvo38 commented on 1-run-automation-test.md
> +  + Select *user Icon* -> 'Profile' (you might find it in the top right conner)
`conner` -> `corner`
Same with below

2018-08-16 11:02 UTC, thangvo38 commented on 1-run-automation-test.md
> +The desired capabilities need to be added to the automation test script in order tests to be executed on the Kobiton device.
```
The desired capabilities need to be added to the automation test script to allow the test to be executed on Kobiton device.
```

2018-08-16 11:02 UTC, thangvo38 commented on 1-run-automation-test.md
> +  npm run android-web-test
Shouldn't it be `android-app-test` instead?

2018-08-16 11:02 UTC, thangvo38 commented on 1-run-automation-test.md
> +### 2.4 Config automatuon test script
`Configure automation`

2018-08-16 13:22 UTC, closed without merging

2018-08-17 08:03 UTC, thangvo38 reviewed
More suggestion to change

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +This part will guide you how to setup TeamCity and configure TeamCity with GitHub. Skip step if you already have TeamCity setup.
Write a sentence to remind the readers that they will have to prepare an empty Github **automation test* repository.

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +  + Select *user Icon* -> 'Profile' (you might find it in the top right conner)
```
**"Profile"**
```

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +  + Select *user Icon* -> 'Settings' (you might find it in the top right conner)
Same as above

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +  app:                {your_app_id},
```
app: '<APP_URL'>
```

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +![alt text](./assets/session.png )
Change image

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +## 2. Config automation test script
`Configure`

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +### 2.3 Config TeamCity project
`Configure`

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +  + On the left hand side, you can select your preferred language, App Type, etc.
Tell the user to choose **"Hybrid/Native from Apps"**

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> ++ [1. Config TeamCity and integrate with GitHub](#1-config-teamcity-and-integrate-with-github)
`Configure`

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> ++ [2. Config automation test script](#2-config-automation-test-script)
`Configure`

2018-08-17 08:03 UTC, thangvo38 commented on 1-run-automation-test.md
> +## 1. Config TeamCity and integrate with GitHub
`Configure`