TeamCity-HockeyApp-Kobiton
kobiton/TeamCity-Appium-ReactNative pull request #5
Opened 2018-08-29 08:39 UTC by phanthaoIT

2018-08-29 10:23 UTC, thangvo38 requested changes
Review

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +HockeyApp is a service that allows developers to recruit and manage testers, distribute apps, and collect crash reports, among other things.
This should be in `README.md`

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +To get the app download URL, we have provided a script written in NodeJS. After executing that script, you will get download URL of that app, which will be used in the next step.
Please be more specific. The script is used to get the `latest` app version.

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +  + Kobiton automatically translates your desired capabilities into code based on the options you selected. Simply copy and paste this code into your test script under the Input Capabilities section.
`Simply copy and paste this code...` What code?
Put this paragraph after you point of the desiredCaps code (next paragraph)

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +Add an environment variable named `APP_URL`, replace `desiredCaps` in the script with the ones collected in the previous step. Then, replace `app` value of `desiredCaps` with the `app_url` variable.
1) `Add an environment variable named APP_URL` -> this doesn't sound to clear.
Suggestion: `Import the env variable APP_URL`
2) `app value of desiredCaps` -> `value of app element in desiredCaps` . Remember `app` alone  is a key/element, not a value

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +>Note: Here are the variables we need. For the sake of this guideline, please set the name for these variables like below.
Remove all `>` this is block because it's important information

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +>APP_URL: You need put empty value of this variable
Please verify if we should remove this as we discussed

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +**Follow steps below to setup TeamCity for automation testing.**
** Setup TeamCity for automation testing **

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +>Note: In this example, we will be running Android App Testing. Therefore, we will use `android-app-test` script.
You should write this before we replace our desiredCaps.
Consider these 2 suggestions: 
1) Move this part to above section
2) Add this part to above section and rewrite this as a reminder to users

2018-08-29 10:23 UTC, thangvo38 commented on run-automation-test.md
> +  APP_URL=$(node hockeyAppApi)
Fix this as we discussed

2018-08-30 04:54 UTC, blackheat commented on README.md
> ++ HockeyApp to keep all application builds
```
HockeyApp to store and distribute application builds
```

2018-08-30 04:54 UTC, blackheat commented on run-automation-test.md
> +  + Kobiton automatically translates your desired capabilities into code based on the options you selected. Simply copy and paste this code into your test script under the Input Capabilities section.
translates ???

2018-08-30 04:54 UTC, blackheat commented on run-automation-test.md
> +Use Kobiton’s desired capabilities settings to configure your test scripts. Our settings include all the required configurations you need to automate your test using the Appium Framework and to run y
?? This line is confusing

2018-08-30 04:54 UTC, blackheat commented on run-automation-test.md
> +### 3.3 Configure automation test script
If you don't tell them to **use** the samples, at least give them a link to the tutorial on how to write test scripts :)

2018-08-30 04:54 UTC, blackheat commented on run-automation-test.md
> +>Note: In this example, we will be running Android App Testing. Therefore, we will use `android-app-test` script.
What if they use iOS ?

2018-08-30 07:59 UTC, thangvo38 requested changes
Please take a look

2018-08-30 07:59 UTC, thangvo38 commented on README.md
> +This guide will demonstrate [how to run automation tests on your app with the Kobiton service](run-automation-test.md)
Change the name. This guide demonstrate more than just `run automation test`

2018-08-30 07:59 UTC, thangvo38 commented on README.md
> +# TeamCity-HockeyApp-Appium-ReactNative
Please change the title, this doesn't look nice

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +## Prerequisites
HockeyApp account?

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +## 2. Getting required parameters
Put a brief instruction for the whole section here would be nicer.

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +  In this example, we use **NodeJS** as the default language of the script. Therefore, choose **NodeJS** in `Language` section and **Hybrid/Native from Apps** in `App type` section. On the right-hand
`Kobiton automatically translates your desired capabilities into code`
Using `translates` here feels odd. Use `generates` instead

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +Use Kobiton’s desired capabilities settings to configure your test scripts. Our settings include all the required configurations you need to automate your test using the Appium Framework and to run y
Fix this as we discussed

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +Replace `desiredCaps` in the script with the ones collected in the previous step. Then,replace value of `app` element in `desiredCaps` with the `APP_URL` environment variable (The value of `app` elem
Duplicated `the value of app element`

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +### 3.3 Configure TeamCity project
I don't see the part where we mention the user's deploying process. Please at least mention or show a picture of 2 build step to highlight that the testing step occurs after deploying step.

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +>Note: url=$(node getAppUrl): this command is required to get the app download URL and set value of url.
Explain `getAppUrl` is the `path to the node application`.
Reminder: This is how a directory tree in a react native project look like:
```
root
----- react native
----- testscript
```
We aren't 100% sure that the test script is in the root folder of the repo, so tell them to access the file by `path`, not just `name`

2018-08-30 07:59 UTC, thangvo38 commented on run-automation-test.md
> +> Note: In this guideline, we will use the Node.js sample (samples/javascript folder) as an example. In sample/javascript folder, we will use `android-app-test` script. You can choose `android-app-te
Fix this as we discussed

2018-08-31 09:23 UTC, closed without merging